- name: conditions testing
  hosts: localhost
  become: yes
  tasks:
  - name: checking user presence
    ansible.builtin.command: id roboshop
    register: user
    ignore_errors: true
  - name: print variable
    ansible.builtin.debug:
     msg: "user output is {{user}}"
  - name: print exit status
    ansible.builtin.debug:
     msg: "exit status is{{user.rc}}"
  - name: creating user
    ansible.builtin.user:
     name: roboshop
    when: user.rc ! 0 