- name: variables concept pkaybook
  hosts: localhost
  vars_files:
  - filevar.yaml
  tasks:
  - name: checkign variables
    ansible.builtin.debug:
      msg: "this is {{course}} course and duration is {{duration}}"