- name: installing nignx
  hosts: localhost
  tasks:
  - name: nignx
    ansible.builtin.package:
      name: nginx
      state: present
  - name: start service
    ansible.builtin.service:
      name: nginx
      state: started
  - name:  mysql
    ansible.builtin.package:
      name: mysql
      state: present
  - name: start service
    ansible.builtin.service:
      name: nginx
      state: started