- name: installing nignx
  hosts: localhost
  become: yes
  tasks:
  - name: nignx
    ansible.builtin.package:
      name: 
      - git
      - postfix
      state: present
  - name: start service
    ansible.builtin.service:
      name: 
      - git
      - postfix
      state: started
  