- name: variables concept pkaybook
  hosts: localhost
  vars: # playlevel
    course: "DevOps"
    duration: 110
  tasks:
  - name: checkign variables
    vars: #task level
      course: "task level"
      duration: 90
    ansible.builtin.debug:
      msg: "this is {{course}} course and duration is {{duration}}"